### PR TITLE
Update NeoScan

### PR DESCRIPTION
**Pull request by adrienmo**
## Problem
Neoscan is outdated because new version separate block syncing with api/web function

## Solution

docker-compose.yml is updated, status is updated to look for 7 services

## Notes

- [x] Remember to bump the `VERSION` file using [semver](https://semver.org/) 📝
- [x] Make sure the CI tests pass on your branch 👍

### CODE REVIEW

**Comment by jeroenptrs** [comment]
neoscan appears to get stuck when minting tokens. Investigating this some more as per our convo in discord

**Comment by revett** [comment]
@jeroenptrs Is this PR blocked until that issue is resolved?

**Comment by jeroenptrs** [comment]
@revett not really. It works the same as before, just the fact that minting tokens *doesnt* work right now (or at least using the c# example).

**Comment by revett** [comment]
@corck I'll do that in a subsequent PR, thanks 👍

**Pull request merged**
