### PR TITLE
Add MIN_BLOCK to .env

### PR DESCRIPTION
**Pull request by archaengel**
## Problem
neo-local-faucet service fails to process request from any wallet with default env variable BOOTSTRAP=_4kBlocks. Chain height of < 5000 breaks service and cause infinite loop in container.
...

## Solution
Add MIN_BLOCK=2500 to .env file
...

## Checklist

- [x] I have run the tests locally.
- [x] I branched off of the `develop` branch and not `master`.
- [x] I did not change the `VERSION` file.

### CODE REVIEW

**Comment by nunojusto** [comment]
I cannot replicate the problem you say.
You ned to wait a bit to neo-faucet gets synced to the current block, but after it's all OK.
See attach screenshot.

image

**Comment by archaengel** [comment]
My apologies, I may have described the issue poorly. 


The faucet status check passes, but submitting a request to the wallet (on the develop branch) has fails for me on my local system and in a clean EC2 instance.


In the [neo-local-faucet](https://github.com/CityOfZion/neo-local-faucet) repo, the [`checkAddress`](https://github.com/CityOfZion/neo-local-faucet/blob/master/src/server/checkAddress.js) function
```js
while (!found && currentIteratedBlock > maxBlock){..}
``` 
is used to check that the last transaction was recorded the chain at some greater than the a given number of blocks ago. At the bottom of the loop, `currentIteratedBlock` is set to the block height of the last transaction sent from the faucet wallet.


This number of blocks is the value of `MIN_BLOCK` variable, which defaults to 5000 in line 5 of the server's [variables file](https://github.com/CityOfZion/neo-local-faucet/blob/master/src/server/variables.js) as the `minBlocks` var imported in the check address file.


The value of `maxBlock` will be negative if the height of the chain is lower than the value of minBlocks; 
```js
 const {
      data: { height }
    } = await get(`${neoscanAddress}/v1/get_height`);
const maxBlock = height - minBlocks;
```
so `!found && currentIteratedBlock > maxBlock` always evaluates to true.

`checkAddress` then gets imported into the [`faucet request endpoint`](https://github.com/CityOfZion/neo-local-faucet/blob/master/src/server/endpoints/requestFaucet.js) which is hit when a user clicks the request button on the [address form](https://github.com/CityOfZion/neo-local-faucet/blob/master/src/components/App/addressForm.js).

I fear I now may have over-explained/over-complicated, so apologies for that, as well.
:stuck_out_tongue:

I've attached a gist below with what I believe are relevant parts of code along with the original files.

***
  * [**MIN_BLOCK default and checkStatus.js, and requestFaucet.js gist**](https://gist.github.com/archaengel/b0a3062f4f98394f51a7f4198d83f2be)
  * [**neo-local-faucet/src/components/App/addressForm.js**](https://github.com/CityOfZion/neo-local-faucet/blob/master/src/components/App/addressForm.js)
  * [**neo-local-faucet/src/server/checkAddress.js**](https://github.com/CityOfZion/neo-local-faucet/blob/master/src/server/checkAddress.js)
  * [**neo-local-faucet/src/server/variables.js**](https://github.com/CityOfZion/neo-local-faucet/blob/master/src/server/variables.js)
  * [**neo-local-faucet/src/server/endpoints/requestFaucet.js**](https://github.com/CityOfZion/neo-local-faucet/blob/master/src/server/endpoints/requestFaucet.js)

**Comment by nunojusto** [comment]
Ok, I understood. We can have here two solutions:
1- Produce new images with more than 5k blocks and add that option to neo-local as a selector of chain
2- Override the neo-local-faucet

And I like the first version, because it's more clean, without env vars doing the hack.
I will produce a new chain and commit the change.
Thanks @archaengel. Very nice investigation.

**Comment by archaengel** [comment]
Much cleaner, indeed. 

The first tx from the faucet address occurs at a height around 1300, so the chain will have to be ~6300 blocks tall before a request will make it through, just to help stem any headaches on your end.

It was a pleasure, thank you for the review 👍

**Pull request closed without merging**
