### PR TITLE
Update issue templates

### PR DESCRIPTION
**Pull request by alloro**
Resolve: #59

### CODE REVIEW

**Comment by revett** [comment]
Thanks for the PR @alloro! Can you please update your branch with `master`. Out of interest what did you base these templates on?

**Comment by jeroenptrs** [comment]
@revett if you look for Github Issue Templates, there's repos with tons of them!

**Comment by alloro** [comment]
@revett Github actually offers a neat documentation and [automatic setup](https://help.github.com/articles/creating-issue-templates-for-your-repository/)

**Comment by jeroenptrs** [comment]
@alloro do make sure you use the PR template when opening a PR.

I've added our checklist back in, make sure you bump VERSION ;)

**Pull request merged**
